ALT_DEVICE_FAMILY ?= soc_cv_av
SOCEDS_ROOT = c:/intelFPGA_lite/18.1/embedded
HWLIBS_ROOT = $(SOCEDS_ROOT)/ip/altera/hps/altera_hps/hwlib
CROSS_COMPILE = arm-linux-gnueabihf-
CFLAGS = -g -Wall  \
       	 -D$(ALT_DEVICE_FAMILY) \
	 -I$(HWLIBS_ROOT)/include/$(ALT_DEVICE_FAMILY)   \
	 -I$(HWLIBS_ROOT)/include/ \
	 -I../../hal_bsp

hpsslave: main.c
	arm-linux-gnueabihf-gcc $(CFLAGS) main.c -o hpsslave
	
clean:
	rm -f *.o hpsslave